#!/bin/sh
set -eu

exec 2>&1

exec s6-setuidgid docker env \
    XDG_CONFIG_HOME=/opt/sonaive/data/caddy/config \
    XDG_DATA_HOME=/opt/sonaive/data/caddy/data \
    HOME=/opt/sonaive/data/caddy/home \
    /opt/sonaive/caddy/caddy run --config /opt/sonaive/caddy/caddyfile --adapter caddyfile
